global:
  ownerReferences: []

defaultStorage:
  create: true
  name: "hive"
  isDefault: true
  type: "hive"
  hive:
    # Unmanaged because default is created by Hive, not us
    unmanagedDatabase: true
    databaseName: "default"
    # databaseName: "metering"
    # location: "hdfs://hdfs-namenode-proxy:9820/operator_metering/storage/"

permissions:
  meteringViewers: []
  meteringAdmins: []
  reportingAdmins: []
  reportingViewers: []
  reportExporters: []

monitoring:
  enabled: true
  namespace: openshift-monitoring
  createRBAC: true

openshift-reporting:
  enabled: true

reporting-operator:
  spec:
    config:
      prometheusURL: "https://prometheus-k8s.openshift-monitoring.svc:9091/"
      tls:
        enabled: true
        createSecret: false
        secretName: "reporting-operator-api-tls-secrets"
      metricsTLS:
        enabled: true
        createSecret: false
        secretName: "reporting-operator-metrics-tls-secrets"
    service:
      annotations:
        "service.alpha.openshift.io/serving-cert-secret-name": "reporting-operator-api-tls-secrets"
    metricsService:
      annotations:
        "service.alpha.openshift.io/serving-cert-secret-name": "reporting-operator-metrics-tls-secrets"
    image:
      tag: latest

presto:
  spec:
    presto:
      config:
        maxQueryLength: "10000000"
      securityContext:
        fsGroup: null
    hive:
      securityContext:
        fsGroup: null
      config:
        metastoreWarehouseDir: "hdfs://hdfs-namenode-proxy:9820/operator_metering/default_hive_warehouse/"
hdfs:
  enabled: true
  spec:
    config:
      datanodeDataDirPerms: "775"

    securityContext:
      fsGroup: null

superset:
  enabled: false
  datasources:
  - fileName: "metering-presto.yaml"
    content: |-
      databases:
      - allow_ctas: true
        database_name: metering-presto
        expose_in_sqllab: true
        extra: "{\r\n    \"metadata_params\": {},\r\n    \"engine_params\": {},\r\n    \"\
          metadata_cache_timeout\": {},\r\n    \"schemas_allowed_for_csv_upload\": []\r\n\
          }\r\n"
        sqlalchemy_uri: presto://presto:8080
        tables: []
