apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  # If you want to use S3 for storage of reports, and collected metrics, edit
  # the hive metastoreWarehouseDir below, and set awsAccessKeyID and
  # awsSecretAccessKey for reporting-operator and presto

  defaultStorage:
    type: "hive"
    hive:
      # Unmanaged because default is created by Hive, not us
      # unmanagedDatabase: true
      # databaseName: "default"
      databaseName: "metering-s3"
      location: "s3a://bucketName/pathInBucket"

  reporting-operator:
    spec:
      config:
        # Replace these with your own AWS credentials
        awsAccessKeyID: "REPLACEME"
        awsSecretAccessKey: "REPLACEME"

  presto:
    spec:
      config:
        # Replace these with your own AWS credentials
        awsAccessKeyID: "REPLACEME"
        awsSecretAccessKey: "REPLACEME"
      hive:
        config:
          useHdfsConfigMap: false
          # Replace this with your bucket
          metastoreWarehouseDir: "s3a://bucketName/pathInBucket"

  hdfs:
    # disable HDFS components when using S3 to avoid wasting resources.
    enabled: false
