apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  defaultStorage:
   type: "hive"
   hive:
     # feel free to adjust the name
     databaseName: "metering-nfs"
     location: "/user/hive/warehouse"
  presto:
    spec:
      config:
        sharedVolume:
          enabled: true
          storage:
            # change REPLACEME to the name of your PVC
            persistentVolumeClaimStorageClass: REPLACEME

  hdfs:
    enabled: false
