apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  hive-site.xml: |
    <configuration>
      <property>
        <name>hive.server2.enable.doAs</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.server2.use.SSL</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.server2.authentication</name>
        <value>NOSASL</value>
      </property>
      <property>
        <name>hive.metastore.uris</name>
        <value>{{ .Values.spec.hive.config.metastoreURIs }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>{{ .Values.spec.hive.config.dbConnectionURL }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>{{ .Values.spec.hive.config.dbConnectionDriver }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>{{ .Values.spec.hive.config.dbConnectionUsername }}</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.spec.hive.config.dbConnectionPassword }}</value>
      </property>
      <property>
        <name>datanucleus.schema.autoCreateAll</name>
        <value>{{ .Values.spec.hive.config.autoCreateMetastoreSchema }}</value>
      </property>
      <property>
        <name>hive.metastore.schema.verification</name>
        <value>{{ .Values.spec.hive.config.enableMetastoreSchemaVerification }}</value>
      </property>
      <property>
        <name>hive.default.fileformat</name>
        <value>{{ .Values.spec.hive.config.defaultFileFormat }}</value>
      </property>
{{- if .Values.spec.hive.config.metastoreClientSocketTimeout }}
      <property>
        <name>hive.metastore.client.socket.timeout</name>
        <value>{{ .Values.spec.hive.config.metastoreClientSocketTimeout }}</value>
      </property>
{{- end }}
{{- if .Values.spec.hive.config.metastoreConnectRetries }}
      <property>
        <name>hive.metastore.connect.retries</name>
        <value>{{ .Values.spec.hive.config.metastoreConnectRetries }}</value>
      </property>
{{- end }}
{{- if .Values.spec.hive.config.metastoreConnectRetryDelaySeconds }}
      <property>
        <name>hive.metastore.client.connect.retry.delay</name>
        <value>{{ .Values.spec.hive.config.metastoreConnectRetryDelaySeconds }}</value>
      </property>
{{- end }}
{{- if .Values.spec.hive.config.transactions.enabled }}
      <property>
        <name>hive.txn.manager</name>
        <value>org.apache.hadoop.hive.ql.lockmgr.DbTxnManager</value>
      </property>
      <property>
        <name>hive.compactor.initiator.on</name>
        <value>true</value>
      </property>
      <property>
        <name>hive.compactor.worker.threads</name>
        <value>2</value>
      </property>
      <property>
        <name>hive.support.concurrency</name>
        <value>true</value>
      </property>
      <property>
        <name>hive.exec.dynamic.partition.mode</name>
        <value>nonstrict</value>
      </property>
{{- end }}
    </configuration>


  hive-log4j2.properties: |
    status = INFO
    name = HiveLog4j2
    packages = org.apache.hadoop.hive.ql.log

    # list of properties
    property.hive.log.level = INFO
    property.hive.root.logger = console
    property.hive.log.dir = ${sys:java.io.tmpdir}/${sys:user.name}
    property.hive.log.file = hive.log

    # list of all appenders
    appenders = console

    # console appender
    appender.console.type = Console
    appender.console.name = console
    appender.console.target = SYSTEM_ERR
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} [%t]: %p %c{2}: %m%n

    # list of all loggers
    loggers = NIOServerCnxn, ClientCnxnSocketNIO, DataNucleus, Datastore, JPOX

    logger.NIOServerCnxn.name = org.apache.zookeeper.server.NIOServerCnxn
    logger.NIOServerCnxn.level = WARN

    logger.ClientCnxnSocketNIO.name = org.apache.zookeeper.ClientCnxnSocketNIO
    logger.ClientCnxnSocketNIO.level = WARN

    logger.DataNucleus.name = DataNucleus
    logger.DataNucleus.level = ERROR

    logger.Datastore.name = Datastore
    logger.Datastore.level = ERROR

    logger.JPOX.name = JPOX
    logger.JPOX.level = ERROR

    # root logger
    rootLogger.level = ${sys:hive.log.level}
    rootLogger.appenderRefs = root
    rootLogger.appenderRef.root.ref = ${sys:hive.root.logger}

  hive-exec-log4j2.properties: |
    status = INFO
    name = HiveLog4j2
    packages = org.apache.hadoop.hive.ql.log

    # list of properties
    property.hive.log.level = INFO
    property.hive.root.logger = console
    property.hive.log.dir = ${sys:java.io.tmpdir}/${sys:user.name}
    property.hive.log.file = hive.log

    # list of all appenders
    appenders = console

    # console appender
    appender.console.type = Console
    appender.console.name = console
    appender.console.target = SYSTEM_ERR
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} [%t]: %p %c{2}: %m%n

    # list of all loggers
    loggers = NIOServerCnxn, ClientCnxnSocketNIO, DataNucleus, Datastore, JPOX

    logger.NIOServerCnxn.name = org.apache.zookeeper.server.NIOServerCnxn
    logger.NIOServerCnxn.level = WARN

    logger.ClientCnxnSocketNIO.name = org.apache.zookeeper.ClientCnxnSocketNIO
    logger.ClientCnxnSocketNIO.level = WARN

    logger.DataNucleus.name = DataNucleus
    logger.DataNucleus.level = ERROR

    logger.Datastore.name = Datastore
    logger.Datastore.level = ERROR

    logger.JPOX.name = JPOX
    logger.JPOX.level = ERROR

    # root logger
    rootLogger.level = ${sys:hive.log.level}
    rootLogger.appenderRefs = root
    rootLogger.appenderRef.root.ref = ${sys:hive.root.logger}

