---

- name: Query Kubernetes for API version
  command: kubectl version -o json
  register: kube_version

- name: Get Kubernetes minor version
  block:
    - name: Log Kubernetes version
      debug:
        msg: |
          Kubernetes Minor Version: {{ kube_minor_version }}
          Kubernetes version at least 1.14: {{ kube_version_at_least_1_14 }}

  vars:
    kube_minor_version: "{{ (kube_version.stdout | from_json | json_query('serverVersion.minor')).rstrip('+') }}"
    kube_version_at_least_1_14: "{{ ((kube_minor_version | int) >= 14) | bool }}"
