---

- name: Validate storage configuration
  fail:
    msg: "Unsupported spec.storage.type, only 'hive' is  a supported option"
  when: meteringconfig_spec | json_query('storage.type') != "hive"

- name: Validate Hive storage configuration
  fail:
    msg: "Invalid spec.storage.hive.type: '{{ hiveStorageType }}', must be one of 's3', or 'sharedPVC'"
  vars:
    hiveStorageType: "{{ meteringconfig_spec_overrides | json_query('storage.hive.type') }}"
  when: hiveStorageType is undefined or hiveStorageType not in ['s3', 'sharedPVC', 'hdfs']

- name: Configure TLS
  include_tasks: configure_tls.yml

- name: Configure Storage
  include_tasks: configure_storage.yml

- name: Print meteringconfig values
  debug:
    msg: "{{ item }}: {{ lookup('vars', item) }}"
  loop: "{{ vars | dict2items | to_json | from_json | json_query(query) | difference(filtered_vars) }}"
  vars:
    filtered_vars:
      - meteringconfig_spec
      - meteringconfig_spec_overrides
      - meteringconfig_default_values
    query: "[?starts_with(@.key, `meteringconfig_`)].key"

- name: Store MeteringConfig spec into values file
  copy: content="{{ meteringconfig_spec }}" dest=/tmp/metering-values.yaml

- include_tasks: "{{ item }}"
  loop:
    - reconcile_metering.yml
    - reconcile_monitoring.yml
    - reconcile_hdfs.yml
    - reconcile_hive.yml
    - reconcile_presto.yml
    - reconcile_reporting_operator.yml
    - reconcile_reporting.yml
